"""empty message

Revision ID: 869b66d22828
Revises: 04dbbd7e2dbd
Create Date: 2023-08-30 18:40:48.669882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869b66d22828'
down_revision = '04dbbd7e2dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
